language: go

go:
  - 1.14.x

script:
  # -L follow redirects
  # - curl -L https://github.com/bostontrader/oktest/blob/master/test-script.sh | bash
  - source $(curl -L https://github.com/bostontrader/oktest/blob/master/test-script.sh)
