language: go

go:
  - 1.14.x

script:
  # -L follow redirects
  # - curl -L https://github.com/bostontrader/oktest/raw/master/test-script.sh | bash
  source $(curl -L https://raw.githubusercontent.com/bostontrader/oktest/master/test-script.sh)