language: go

go:
  - 1.14.x

script:
  - git clone https://github.com/bostontrader/okconnect
  - cd okconnect
  - go build
  - ./okconnect
  - ./okconnect -cmd help

  - APIKEY="$(curl -X POST http://185.183.96.73:3003/apikeys | jq -r .apikey)"
  - CURRENCY_BTC="$(curl -d 'apikey=$APIKEY&rarity=0&symbol=BTC&title=Bitcoin' http://185.183.96.73:3003/currencies | jq .data.last_insert_id)"
  - CURRENCY_BSV="$(curl -d 'apikey=$APIKEY&rarity=0&symbol=BSV&title=Bitcoin SV' http://185.183.96.73:3003/currencies | jq .data.last_insert_id)"

  - ACCT_EQUITY="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BTC&title=Owners Equity' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"
  - ACCT_LCL_WALLET="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BTC&title=Local Wallet' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"
  - ACCT_FUNDING="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BTC&title=OKEx Funding' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"
  - ACCT_FEE="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BTC&title=Fee' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"
  - ACCT_SPOT_BTC="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BTC&title=OKEx Spot' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"
  - ACCT_SPOT_BSV="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BSV&title=OKEx Spot' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"
  - ACCT_SPOT_HOLD="$(curl -d 'apikey=$APIKEY&rarity=0&currency_id=$CURRENCY_BTC&title=OKEx Spot-Hold' http://185.183.96.73:3003/accounts | jq .data.last_insert_id)"

  - CAT_EQUITY="$(curl -d 'apikey=$APIKEY&symbol=Eq&title=Equity' http://185.183.96.73:3003/categories | jq .data.last_insert_id)"
  - CAT_EXPENSE="$(curl -d 'apikey=$APIKEY&symbol=Eq&title=Expenses' http://185.183.96.73:3003/categories | jq .data.last_insert_id)"
  - CAT_ASSET="$(curl -d 'apikey=$APIKEY&symbol=Eq&title=Assets' http://185.183.96.73:3003/categories | jq .data.last_insert_id)"

  - curl -d 'apikey=$APIKEY&account_id=$ACCT_LCL_WALLET&category_id=$CAT_ASSET' http://185.183.96.73:3003/acctcats
  - curl -d 'apikey=$APIKEY&account_id=$ACCT_FUNDING&category_id=$CAT_ASSET' http://185.183.96.73:3003/acctcats
  - curl -d 'apikey=$APIKEY&account_id=$ACCT_SPOT_BTC&category_id=$CAT_ASSET' http://185.183.96.73:3003/acctcats
  - curl -d 'apikey=$APIKEY&account_id=$ACCT_SPOT_BSV&category_id=$CAT_ASSET' http://185.183.96.73:3003/acctcats
  - curl -d 'apikey=$APIKEY&account_id=$ACCT_SPOT_HOLD&category_id=$CAT_ASSET' http://185.183.96.73:3003/acctcats
  - curl -d 'apikey=$APIKEY&account_id=$ACCT_FEE&category_id=$CAT_EXPENSE' http://185.183.96.73:3003/acctcats
  - curl -d 'apikey=$APIKEY&account_id=$ACCT_EQUITY&category_id=$CAT_EQUITY' http://185.183.96.73:3003/acctcats

  - env